---
- name: System tear down for Proxmox
  hosts: prox
  tasks:
    - name: Stop new container
      community.general.proxmox:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: 
        vmid: 102
        state: stopped
      changed_when: true
    - name: Remove new container
      community.general.proxmox:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: 
        vmid: 102
        state: absent
      changed_when: true
    - name: Gather storage information from Proxmox
      ansible.builtin.command: pvesm zfsscan
      register: zpool
    - name: Print storage information from Proxmox
      ansible.builtin.debug: msg="Your zfs pool is {{ zpool.stdout }}"
    - name: Remove zfs device from zpool
      ansible.builtin.command: pvesm remove {{ item }}
      with_items:
      - ansible
      ignore_errors: true
    - name: Check on progress
      ansible.builtin.command: pvesm status
      register: zfsstatus
    - name: Print status
      ansible.builtin.debug: msg="{{ zfsstatus.stdout_lines }}"