# containers/Containerfile
FROM debian:stable-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl rsync gnupg gpg \
    aptly \
    dnf dnf-plugins-core createrepo-c \
    debian-archive-keyring ubuntu-keyring \
    && rm -rf /var/lib/apt/lists/*

# Keep it simple: entrypoint is bash
CMD ["bash"]
