---
- name: General Proxmox cluster configuration
  hosts: proxmox
  tasks:
    - name: Copy over opnSense ISO
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../isos/OPNsense-23.7-dvd-amd64.iso"
        dest: /var/lib/vz/template/iso/
        owner: root
        group: root
        mode: '0644'
        force: false
    - name: Copy over Security Onion ISO
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../isos/securityonion-2.4.30-20231121.iso"
        dest: /var/lib/vz/template/iso/
        owner: root
        group: root
        mode: '0644'
        force: false
    - name: Copy over Turnkey Containers for C2
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../containers/"
        dest: /var/lib/vz/template/cache/
        owner: root
        group: root
        mode: '0644'
        force: false
    - name: Copy over Templates for opnSense and Security Onion in the form of backups
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../templates/"
        dest: /var/lib/vz/dump/
        owner: root
        group: root
        mode: '0644'
        force: false
