---
- name: Initialize kubernetes infra
  hosts: master  #Kube master
  become: true
  become_user: root
  tasks:
  - name: Initialize kubernetes cluster #Default is 10.244.0.0/16
    shell: |
      kubeadm init --pod-network-cidr=10.244.0.0/16
    register: init_output
  - name: Print the initialization output
    debug: msg="{{ init_output }}"