---
- name: Configure kubectl
  hosts: master #Kube master
  tasks:
  - name: Create a directory if it does not exist
    file:
      path: $HOME/.kube
      state: directory
      mode: '0755'
  - name: Copies admin.conf to user's kube config #Could also be kubelet.conf, make sure to check if having issues
    become: true
    become_user: root
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/bobbymayyy/.kube/config
      remote_src: yes
      owner: bobbymayyy
      group: bobbymayyy