---
- name: Deploy flannel networking policy
  hosts: master #Kube master
  tasks:
  - name: Wait a bit...
    pause:
      seconds: 60
  - name: Download cni plugins archive
    get_url:
      url: https://github.com/containernetworking/plugins/releases/download/v1.2.0/cni-plugins-linux-amd64-v1.2.0.tgz
      dest: /tmp/cni-plugins-linux-amd64-v1.2.0.tgz
      mode: 0644
  - name: Extract cni plugins into /opt/cni/bin
    unarchive:
      src: /tmp/cni-plugins-linux-amd64-v1.2.0.tgz
      dest: /opt/cni/bin
      remote_src: true
  - name: Apply the flannel networking policy definition
    shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  - name: Get the token for joining the worker nodes
    shell: kubeadm token create --print-join-command
    register: kubernetes_join_command
  - name: Print the kubernetes node join command
    debug:
      msg: "{{ kubernetes_join_command.stdout }}"
  - name: Copy join command to local file
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777